### ISSUE TITLE
USER STORY: <View the events list>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#10]
As a **user**, I can **view the future events ordered from today's date** so that ** I can view the events in chronological order **.

## Acceptance Criteria:
- Acceptance Criteria1: Show all the events;
- Acceptance Criteria2: Display the events in chronological order from today's date to the farthest in the future.

## Tasks:
- [ ] Task1: Add an Events page;
- [ ] Task2: Wire up the page in App.js;
- [ ] Task3: Fetch the Events data from the API;
- [ ] Task4: Create and wire up a EventsPage.module.css file for styling.
