### ISSUE TITLE
USER STORY: <Create comments>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#17]
As a **logged-in user**, I can **add comments to an event** so that **I can share my thoughts about the event**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a Create Comment form;
- Acceptance Criteria 2: When the user submits the form with valid data, it creates a new comment.

## Tasks:
- [ ] Tasks1: Create a Comment Create form;
- [ ] Tasks2: Wire up the form in EventPage.js;
- [ ] Tasks3: Send the data to the API to store it in the database;
- [ ] Task4: Create and wire up a CommentCreateEditForm.module.css file for styling.
