### ISSUE TITLE
USER STORY: <View comments>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#18]
As a **user**, I can **read comments left by users under events** so that **I can read what other users think about the events **.

## Acceptance Criteria:
- Acceptance Criteria1: Display the comments under the events;
- Acceptance Criteria2:  Display the comments in chronological order with the most recent at the top;

## Tasks:
- [ ] Task1: Create a Comment component;
- [ ] Task2: In the Event page, fetch the comments data from the API;
- [ ] Task3: Add an infinite scroll component and use it to render all comments in the database.
- [ ] Task4: Create and wire up a Comment.module.css file for styling.
