### ISSUE TITLE
USER STORY: <Profile page>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#20]
As a **user **, I can **view other users' profiles** so that **I can see their posts and learn more about them**.

## Acceptance Criteria:
- Acceptance Criteria1: Display a profile page;
- Acceptance Criteria2: Display on the page all profiles details;

## Tasks:
- [ ] Task1: Create a Profile page;
- [ ] Task2: Wire up the Profile page component to a route in App.js;
- [ ] Task3:  Fetch the data about the profile from the API;
- [ ] Task4: Create and wire up the ProfilePage.module.css file to style the component.
