### ISSUE TITLE
USER STORY: <Edit profile>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#23]
As a **logged-in user** I can **edit my profile** so that **I can change my profile picture and bio **.

## Acceptance Criteria:
- Acceptance Criteria1: Add an edit profile form;
- Acceptance Criteria 2: When the user submits the form with valid data, it updates the profile.
- Acceptance Criteria 4: If a user is not the profile owner, they can't access the form.

## Tasks:
- [ ] Tasks1: Create the ProfileEdit form;
- [ ] Tasks2: Wire up the form in App.js;
- [ ] Tasks3: Request the profile data to the API and send back the updated data.
