### ISSUE TITLE
USER STORY: <Log into the account>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#3]
As a **user**, I can **sign in to the app** so that **I can access functionality for logged-in users**.

## Acceptance Criteria:
- Acceptance Criteria1: Add a sign-in form;
- Acceptance Criteria2: If the user doesn't fill up the form correctly, it should display an error message relative to the issue; 
- Acceptance Criteria3: Once the user is signed in, they should be able to access restricted functionality;
- Acceptance Criteria 4: Once the user is signed in, display different links in the Navbar.

## Tasks:
- [ ] Tasks1: Create a sign-in form;
- [ ] Tasks2: Import the form in App.js;
- [ ] Tasks3: Send the details to the API to validate the log-in;
- [ ] Task4: Wire up the SignInUpForm.module.css file for styling the component;
- [ ] Task5: Use a Context hook to determine the user status and modify the NavBar component to display the links accordingly.
