### ISSUE TITLE
USER STORY: <View categories list>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#32]
As an **admin* , I can **view the categories list** so that **I can which new categories I can add**.

## Acceptance Criteria:
- Acceptance Criteria1: Show all categories.

## Tasks:
- [ ] Task1: Create a Categories Page;
- [ ] Task2: Wire up the Categories Page in App.js;
- [ ] Task3: Fetch the categories data from the API;
- [ ] Task4: Create and wire up a CategoriesPage.module.css file for styling the component if needed.
