### ISSUE TITLE
USER STORY: <View event details>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#6]
As a **user **, I can ** view the details of an event** so that **I can learn more about it**.

## Acceptance Criteria:
- Acceptance Criteria1:  As a user clicks on an Event, it should open the respective Event page;
- Acceptance Criteria2: The Event page should display all Event's details.

## Tasks:
- [ ] Tasks1: Create an event page;
- [ ] Tasks2: Wire up the event page in App.js;
- [ ] Tasks3: In the event page file, fetch the data about the post;
- [ ] Task4: Display the fetched data.
