### ISSUE TITLE
USER STORY: <Manage event>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/drf-api-event#7]
As an **event owner** I can **edit and delete my event** so that ** I can make corrections or update my event after it was created **.

## Acceptance Criteria:
- Acceptance Criteria1: Add an Edit Event form;
- Acceptance Criteria2: When the event owner submits the form with valid data, it updates the event;
- Acceptance Criteria3: When the event owner clicks the delete button, it deletes the event;
- Acceptance Criteria4: If a user is not the event owner, they can't access the form.

## Tasks:
- [ ] Tasks1: Create the Edit Event form;
- [ ] Tasks2: Wire up the form in App.js;
- [ ] Tasks3: Request the event data to the API and send back the updated data;
- [ ] Task4: If the action is deletion, request the event data to the API and delete it;
- [ ] Task5: Wire up the EventCreateEditForm.module.css file for styling the component.
